#!/bin/sh

if command -v paru >/dev/null; then
  exit 0
fi

start="$PWD"
arch_config="$(dirname "$(realpath "$0")")"
cd /tmp || exit 1

sudo pacman -S --needed base-devel

if ! command -v rustup >/dev/null; then
  "$arch_config"/install_rust
fi

[ "$(rustup show active-toolchain | wc -l)" -ne 0 ] || rustup default stable

rm -rf paru
git clone https://aur.archlinux.org/paru.git
cd paru || exit 1

makepkg -si

cd "$start" || exit 1
